from dataclasses import dataclass
from datetime import datetime, date

@dataclass
class Input_Parameter:
    name: str
    required: bool
    alt_format: list
    type: list
    constraints: list

def required_field_names(input_field_list):
    required_fields = filter(lambda x: x.required, input_field_list)
    required_field_names = [x.name for x in required_fields]
    return required_field_names

def make_specs_dictionary(input_field_list):
    result = {}
    for f in input_field_list:
        value = {"required": f.required}
        if len(f.alt_format) > 0:
            value["alt_format"] = f.alt_format
        if f.type is not None:
            value["type"] = f.type
        if f.constraints is not None:
            value["constraints"] = f.constraints
        result[f.name] = value
    return result

def make_specs():
    return [
        Input_Parameter('run_name', required=True, alt_format=[], type=[str], constraints=None),
        Input_Parameter('temp_file_backed_array_directory', required=True, alt_format=[], type=[str], constraints=None),
        Input_Parameter('num_nodes', required=True, alt_format=[], type=[int], constraints=None),
        Input_Parameter('node_areas', required=True, alt_format=['yml', 'csv'], type=[dict, float], constraints=None),
        Input_Parameter('start_date', required=True, alt_format=[], type=[date], constraints=None),
        Input_Parameter('time_periods', required=True, alt_format=['yml', 'csv'], type=[list, list, int], constraints=None),
        Input_Parameter('num_cores', required=False, alt_format=[], type=[int], constraints=None),
        Input_Parameter('output_recharge', required=False, alt_format=[], type=[bool], constraints=None),
        Input_Parameter('output_evt', required=False, alt_format=[], type=[bool], constraints=None),
        Input_Parameter('excess_sw_process', required=True, alt_format=[], type=[str], constraints=['sw_rip', 'sw_ow_evap', 'sw_only', 'disabled']),
        Input_Parameter('ievtcb', required=False, alt_format=[], type=[int], constraints=None),
        Input_Parameter('nevtopt', required=False, alt_format=[], type=[int], constraints=[1, 2, 3]),
        Input_Parameter('evt_parameters', required=False, alt_format=['yml', 'csv'], type=[dict, list], constraints=None),
        Input_Parameter('output_sfr', required=False, alt_format=[], type=[bool], constraints=None),
        Input_Parameter('attenuate_sfr_flows', required=False, alt_format=[], type=[bool], constraints=None),
        Input_Parameter('sfr_flow_zones', required=False, alt_format=['yml', 'csv'], type=[dict, list], constraints=None),
        Input_Parameter('sfr_flow_monthly_proportions', required=False, alt_format=['yml', 'csv'], type=[dict, list], constraints=None),
        Input_Parameter('sfr_obs', required=False, alt_format=[], type=[str], constraints=None),
        Input_Parameter('istcb1', required=False, alt_format=[], type=[int], constraints=None),
        Input_Parameter('istcb2', required=False, alt_format=[], type=[int], constraints=None),
        Input_Parameter('output_individual', required=False, alt_format=[], type=[str], constraints=None),
        Input_Parameter('irchcb', required=False, alt_format=[], type=[int], constraints=None),
        Input_Parameter('nodes_per_line', required=False, alt_format=[], type=[int], constraints=None),
        Input_Parameter('output_fac', required=False, alt_format=[], type=[float], constraints=None),
        Input_Parameter('spatial_output_date', required=False, alt_format=[], type=["spatial_output_date"], constraints=None),
        Input_Parameter('reporting_zone_names', required=False, alt_format=['yml'], type=[dict, str], constraints=None),
        Input_Parameter('reporting_zone_mapping', required=False, alt_format=['yml', 'csv'], type=[dict, int], constraints=None),
        Input_Parameter('rainfall_zone_names', required=False, alt_format=['yml'], type=[dict, str], constraints=None),
        Input_Parameter('rainfall_zone_mapping', required=True, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('pe_zone_names', required=False, alt_format=['yml'], type=[dict, str], constraints=None),
        Input_Parameter('pe_zone_mapping', required=True, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('temperature_zone_names', required=False, alt_format=['yml'], type=[dict, str], constraints=None),
        Input_Parameter('temperature_zone_mapping', required=False, alt_format=['yml', 'csv'], type=[dict, float], constraints=None),
        Input_Parameter('tmax_c_zone_names', required=False, alt_format=['yml'], type=[dict, str], constraints=None),
        Input_Parameter('tmax_c_zone_mapping', required=False, alt_format=['yml', 'csv'], type=[dict, float], constraints=None),
        Input_Parameter('tmin_c_zone_names', required=False, alt_format=['yml'], type=[dict, str], constraints=None),
        Input_Parameter('tmin_c_zone_mapping', required=False, alt_format=['yml', 'csv'], type=[dict, float], constraints=None),
        Input_Parameter('windsp_zone_names', required=False, alt_format=['yml'], type=[dict, str], constraints=None),
        Input_Parameter('windsp_zone_mapping', required=False, alt_format=['yml', 'csv'], type=[dict, float], constraints=None),
        Input_Parameter('subroot_zone_names', required=False, alt_format=['yml'], type=[dict, str], constraints=None),
        Input_Parameter('subroot_zone_mapping', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('rapid_runoff_zone_names', required=False, alt_format=['yml'], type=[dict, str], constraints=None),
        Input_Parameter('rapid_runoff_zone_mapping', required=False, alt_format=['yml', 'csv'], type=[dict, int], constraints=None),
        Input_Parameter('interflow_zone_names', required=False, alt_format=['yml'], type=[dict, str], constraints=None),
        Input_Parameter('interflow_zone_mapping', required=False, alt_format=['yml', 'csv'], type=[dict, int], constraints=None),
        Input_Parameter('swrecharge_zone_names', required=False, alt_format=['yml'], type=[dict, str], constraints=None),
        Input_Parameter('swrecharge_zone_mapping', required=False, alt_format=['yml', 'csv'], type=[dict, int], constraints=None),
        Input_Parameter('sw_zone_names', required=False, alt_format=['yml'], type=[dict, str], constraints=None),
        Input_Parameter('sw_zone_mapping', required=False, alt_format=['yml', 'csv'], type=[dict, int], constraints=None),
        Input_Parameter('macropore_zone_names', required=False, alt_format=['yml'], type=[dict, str], constraints=None),
        Input_Parameter('macropore_zone_mapping', required=False, alt_format=['yml', 'csv'], type=[dict, int], constraints=None),
        Input_Parameter('soil_zone_names', required=False, alt_format=['yml'], type=[dict, str], constraints=None),
        Input_Parameter('landuse_zone_names', required=False, alt_format=['yml'], type=[dict, str], constraints=None),
        Input_Parameter('canopy_process', required=True, alt_format=[], type=[str], constraints=['enabled', 'disabled']),
        Input_Parameter('canopy_zone_names', required=False, alt_format=['yml'], type=[dict, str], constraints=None),
        Input_Parameter('canopy_zone_mapping', required=False, alt_format=['yml', 'csv'], type=[dict, int], constraints=None),
        Input_Parameter('free_throughfall', required=False, alt_format=['yml', 'csv'], type=[dict, float], constraints=None),
        Input_Parameter('max_canopy_storage', required=False, alt_format=['yml', 'csv'], type=[dict, float], constraints=None),
        Input_Parameter('snow_process_simple', required=True, alt_format=[], type=[str], constraints=['enabled', 'disabled']),
        Input_Parameter('snow_params_simple', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('snow_process_complex', required=True, alt_format=[], type=[str], constraints=['enabled', 'disabled']),
        Input_Parameter('snow_params_complex', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('rapid_runoff_process', required=True, alt_format=[], type=[str], constraints=['enabled', 'disabled']),
        Input_Parameter('rapid_runoff_params', required=False, alt_format=['yml'], type=[list, dict, list], constraints=None),
        Input_Parameter('swrecharge_process', required=True, alt_format=[], type=[str], constraints=['enabled', 'disabled']),
        Input_Parameter('swrecharge_proportion', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('swrecharge_limit', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('single_cell_swrecharge_process', required=True, alt_format=[], type=[str], constraints=['enabled', 'disabled']),
        Input_Parameter('single_cell_swrecharge_zone_names', required=False, alt_format=['yml'], type=[dict, str], constraints=None),
        Input_Parameter('single_cell_swrecharge_zone_mapping', required=False, alt_format=['yml', 'csv'], type=[dict, int], constraints=None),
        Input_Parameter('single_cell_swrecharge_proportion', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('single_cell_swrecharge_limit', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('single_cell_swrecharge_activation', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('macropore_process', required=True, alt_format=[], type=[str], constraints=['enabled', 'disabled']),
        Input_Parameter('macropore_activation_option', required=False, alt_format=[], type=[str], constraints=['SMD', 'RI']),
        Input_Parameter('macropore_proportion', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('macropore_limit', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('macropore_activation', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('macropore_recharge', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('fao_process', required=True, alt_format=[], type=[str], constraints=['enabled', 'disabled']),
        Input_Parameter('fao_input', required=False, alt_format=[], type=[str], constraints=['ls', 'l']),
        Input_Parameter('soil_static_params', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('smd', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('soil_spatial', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('lu_spatial', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('zr', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('kc', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('taw', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('raw', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('percolation_rejection', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('percolation_rejection_ts', required=False, alt_format=['yml', 'csv'], type=[list, list, float], constraints=None),
        Input_Parameter('percolation_rejection_use_timeseries', required=False, alt_format=[], type=[bool], constraints=None),
        Input_Parameter('subroot_leakage_process', required=True, alt_format=[], type=[str], constraints=['enabled', 'disabled']),
        Input_Parameter('subroot_leakage_fraction', required=False, alt_format=['yml', 'csv'], type=[dict, float], constraints=None),
        Input_Parameter('interflow_process', required=True, alt_format=[], type=[str], constraints=['enabled', 'disabled']),
        Input_Parameter('init_interflow_store', required=False, alt_format=['yml', 'csv'], type=[dict, float], constraints=None),
        Input_Parameter('interflow_store_bypass', required=False, alt_format=['yml', 'csv'], type=[dict, float], constraints=None),
        Input_Parameter('infiltration_limit', required=False, alt_format=['yml', 'csv'], type=[dict, float], constraints=None),
        Input_Parameter('interflow_decay', required=False, alt_format=['yml', 'csv'], type=[dict, float], constraints=None),
        Input_Parameter('infiltration_limit_use_timeseries', required=False, alt_format=[], type=[bool], constraints=None),
        Input_Parameter('interflow_decay_use_timeseries', required=False, alt_format=[], type=[bool], constraints=None),
        Input_Parameter('infiltration_limit_ts', required=False, alt_format=['yml', 'csv'], type=[list, list, float], constraints=None),
        Input_Parameter('interflow_decay_ts', required=False, alt_format=['yml', 'csv'], type=[list, list, float], constraints=None),
        Input_Parameter('recharge_attenuation_process', required=True, alt_format=[], type=[str], constraints=['enabled', 'disabled']),
        Input_Parameter('recharge_attenuation_params', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('recharge_node_mapping', required=False, alt_format=['yml', 'csv'], type=[dict, list, int], constraints=None),
        Input_Parameter('historical_solute_process', required=True, alt_format=[], type=[str], constraints=['enabled', 'disabled']),
        Input_Parameter('historical_mi_array_kg_per_time_period', required=False, alt_format=['yml', 'csv'], type=[float], constraints=None),
        Input_Parameter('historical_start_date', required=False, alt_format=[], type=[datetime], constraints=None),
        Input_Parameter('historical_time_periods', required=False, alt_format=['yml', 'csv'], type=[list, list, int], constraints=None),
        Input_Parameter('solute_process', required=True, alt_format=[], type=[str], constraints=['enabled', 'disabled']),
        Input_Parameter('solute_calibration_a', required=False, alt_format=[], type=[float], constraints=None),
        Input_Parameter('solute_calibration_mu', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('solute_calibration_sigma', required=False, alt_format=[], type=[float], constraints=None),
        Input_Parameter('solute_calibration_alpha', required=False, alt_format=[], type=[float], constraints=None),
        Input_Parameter('solute_calibration_effective_porosity', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('solute_depth_to_water', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('solute_loading', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('sw_process', required=True, alt_format=[], type=[str], constraints=['enabled', 'disabled']),
        Input_Parameter('sw_params', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('sw_ponding_process', required=True, alt_format=[], type=[str], constraints=['enabled', 'disabled']),
        Input_Parameter('sw_init_ponding', required=False, alt_format=[], type=[float], constraints=None),
        Input_Parameter('sw_max_ponding', required=False, alt_format=[], type=[float], constraints=None),
        Input_Parameter('sw_ponding_area', required=False, alt_format=['yml', 'csv'], type=[dict, float], constraints=None),
        Input_Parameter('sw_downstream', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('sw_activation', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('sw_bed_infiltration', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('sw_direct_recharge', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('sw_pe_to_open_water', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('routing_process', required=False, alt_format=[], type=[str], constraints=['enabled', 'disabled']),
        Input_Parameter('routing_topology', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('rainfall_ts', required=True, alt_format=['yml', 'csv'], type=[list, list, float], constraints=None),
        Input_Parameter('pe_ts', required=False, alt_format=['yml', 'csv'], type=[list, list, float], constraints=None),
        Input_Parameter('temperature_ts', required=False, alt_format=['yml', 'csv'], type=[list, list, float], constraints=None),
        Input_Parameter('tmax_c_ts', required=False, alt_format=['yml', 'csv'], type=[list, list, float], constraints=None),
        Input_Parameter('tmin_c_ts', required=False, alt_format=['yml', 'csv'], type=[list, list, float], constraints=None),
        Input_Parameter('windsp_ts', required=False, alt_format=['yml', 'csv'], type=[list, list, float], constraints=None),
        Input_Parameter('subroot_leakage_ts', required=False, alt_format=['yml', 'csv'], type=[list, list, float], constraints=None),
        Input_Parameter('swdis_ts', required=False, alt_format=['yml', 'csv'], type=[list, list, float], constraints=None),
        Input_Parameter('swdis_locs', required=False, alt_format=['yml', 'csv'], type=[dict, int], constraints=None),
        Input_Parameter('swabs_ts', required=False, alt_format=['yml', 'csv'], type=[list, list, float], constraints=None),
        Input_Parameter('swabs_locs', required=False, alt_format=['yml', 'csv'], type=[dict, int], constraints=None),
        Input_Parameter('swdis_f', required=False, alt_format=[], type=[int], constraints=[0, 1, 2]),
        Input_Parameter('swabs_f', required=False, alt_format=[], type=[int], constraints=[0, 1, 2]),
        Input_Parameter('gwmodel_type', required=False, alt_format=[], type=[str], constraints=['mf6', 'mfusg', 'mf96']),
        Input_Parameter('mf96_lrc', required=False, alt_format=[], type=[list, int], constraints=None),
        Input_Parameter('version', required=True, alt_format=[], type=[int], constraints=None),
        Input_Parameter('node_xy', required=False, alt_format=['yml', 'csv'], type=[dict, list, float], constraints=None),
        Input_Parameter('disv', required=False, alt_format=[], type=[bool], constraints=None),
    ]
