import datetime
import unittest
import swacmod.finalization as finalization

class Test_Historical_Nitrate_Finalization(unittest.TestCase):
	def test_fin_historical_start_date_when_valid(self):
		data = {
			"params" : {
				"historical_start_date" : "2024-01-16",
			}
		}
		name = "historical_start_date"
		finalization.fin_historical_start_date(data, name)

		actual = data["params"]["historical_start_date"]
		expected = datetime.datetime(2024, 1, 16)
		self.assertEqual(expected, actual)

	def test_finalize_param_converts_historical_start_date_when_valid(self):
		data = {
			"params" : {
				"num_cores" : 1,
				"output_individual" : "none",
				"output_recharge" : False,
				"run_name" : "aardvark",
				"start_date" : "2000-01-01",
				"irchcb" : 50,
				"nodes_per_line" : 10,
				"output_fac" : 1.0,
				"spatial_output_date" : None,
				"reporting_zone_mapping" : None,
				"num_nodes" : 1,
				"reporting_zone_names" : None,
				"rainfall_zone_names" : None,
				"rainfall_zone_mapping" : {},
				"pe_zone_names" : None,
				"pe_zone_mapping" : {},
				"temperature_zone_mapping" : None,
				"pe_zone_mapping" : {},
				"temperature_zone_names" : None,
				"tmin_c_zone_mapping" : None,
				"tmin_c_zone_names" : None,
				"tmax_c_zone_mapping" : None,
				"tmax_c_zone_names" : None,
				"windsp_zone_mapping" : None,
				"windsp_zone_names" : None,
				"snow_params_complex" : None,
				"subroot_zone_mapping" : None,
				"subroot_zone_names" : None,
				"rapid_runoff_zone_names" : None,
				"interflow_zone_mapping" : None,
				"swrecharge_zone_mapping" : None,
				"swrecharge_zone_names" : None,
				"single_cell_swrecharge_zone_names" : None,
				"single_cell_swrecharge_proportion" : None,
				"single_cell_swrecharge_limit" : None,
				"single_cell_swrecharge_activation" : None,
				"macropore_zone_mapping" : None,
				"macropore_activation_option" : None,
				"macropore_zone_names" : None,
				"soil_zone_names" : None,
				"rapid_runoff_zone_mapping" : None,
				"interflow_zone_names" : None,
				"interflow_decay" : None,
				"interflow_store_bypass" : None,
				"infiltration_limit" : None,
				"infiltration_limit_ts" : None,
				"infiltration_limit_use_timeseries" : None,
				"interflow_decay_ts" : None,
				"interflow_decay_use_timeseries" : None,
				"recharge_attenuation_params" : None,
				"sw_params" : None,
				"sw_zone_names" : None,
				"sw_init_ponding" : None,
				"ponding_area" : None,
				"sw_pe_to_open_water" : None,
				"sw_direct_recharge" : None,
				"sw_activation" : None,
				"sw_bed_infiltration" : None,
				"sw_downstream" : None,
				"output_sfr" : None,
				"sfr_obs" : None,
				"istcb1" : None,
				"istcb2" : None,
				"routing_process" : None,
				"routing_topology" : None,
				"swdis_locs" : None,
				"swabs_locs" : None,
				"swdis_f" : None,
				"swabs_f" : None,
				"init_interflow_store" : None,
				"single_cell_swrecharge_zone_mapping" : None,
				"macropore_zone_names" : None,
				"landuse_zone_names" : None,
				"canopy_zone_mapping" : None,
				"canopy_zone_names" : None,
				"free_throughfall" : None,
				"max_canopy_storage" : None,
				"rapid_runoff_params" : None,
				"swrecharge_proportion" : None,
				"swrecharge_limit" : None,
				"macropore_proportion" : None,
				"macropore_limit" : None,
				"macropore_activation" : None,
				"macropore_recharge" : None,
				"soil_static_params" : {
					"FC" : [0],
					"WP" : [0],
					"p" : [0],
				},
				"soil_spatial" : {1 : [0]},
				"lu_spatial" : {1 : []},
				"zr" : {1 : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]},
				"kc" : None,
				"taw" : {
					1: [], 
					2: [], 
					3: [], 
					4: [], 
					5: [], 
					6: [], 
					7: [], 
					8: [], 
					9: [], 
					10: [], 
					11: [], 
					12: [], 
				},
				"raw" : {
					1: [], 
					2: [], 
					3: [], 
					4: [], 
					5: [], 
					6: [], 
					7: [], 
					8: [], 
					9: [], 
					10: [], 
					11: [], 
					12: [], 
				},
				"percolation_rejection" : None,
				"soil_zone_names" : None,
				"swrecharge_process" : "disabled",
				"fao_process" : "disabled",
				"fao_input" : "l",
				"landuse_zone_names" : {},
				"percolation_rejection_use_timeseries" : None,
				"subsoilzone_leakage_fraction" : None,
				"init_interflow_store" : None,
				"infiltration_limit" : None,
				"interflow_decay" : None,
				"sw_zone_mapping" : None,
				"sw_zone_names" : None,
				"sw_init_ponding" : None,
				"sw_ponding_area" : None,
				"sw_pe_to_open_water" : None,
				"sw_direct_recharge" : None,
				"sw_activation" : None,
				"sw_bed_infiltration" : None,
				"sw_downstream" : None,
				"output_sfr" : None,
				"sfr_obs" : None,
				"istcb1" : None,
				"istcb2" : None,
				"routing_process" : None,
				"routing_topology" : None,
				"swdis_locs" : None,
				"swabs_locs" : None,
				"swdis_f" : None,
				"swabs_f" : None,
				"output_evt" : None,
				"excess_sw_process" : None,
				"gwmodel_type" : None,
				"evt_parameters" : None,
				"ievtcb" : None,
				"nevtopt" : None,
				"infiltration_limit_use_timeseries" : None,
				"disv" : None,

				"historical_start_date" : "2024-01-16",
			}
		}
		finalization.finalize_params(data)

		actual = data["params"]["historical_start_date"]
		expected = datetime.datetime(2024, 1, 16)
		self.assertEqual(expected, actual)
