import unittest
import swacmod.model as m
import warnings
import swacmod.input_output as input_output
import test.file_test_helpers as file_test_helpers

class Test_Get_Sfr_File(unittest.TestCase):
	def test_x(self):
		run_name = "sfr-mfusg-aardvark"
		gwmodel_type = "mfusg"
		filename = "output_files/sfr-mfusg-aardvark.sfr"
		expected = """# SFR package for  MODFLOW-USG, generated by SWAcMod.
reachinput 
3 3 0 0 86400.00000000 0.00010000 0 0 1 
30 1 1 40.0 60.0 1e-04 70.0 80.0
30 2 1 40.0 60.0 1e-04 70.0 80.0
30 3 1 40.0 60.0 1e-04 70.0 80.0
3 0 0
1 0 1 0 0.0 0.0 0.0 0.0 
100.0 90.0 
100.0 90.0 
2 0 2 0 0.0 1.4 0.0 0.0 
100.0 90.0 
100.0 90.0 
3 0 3 0 0.0 3.3 0.0 0.0 
100.0 90.0 
100.0 90.0 
3 0 0
1 0 1 0 0.0 0.0 0.0 0.0 
100.0 90.0 
100.0 90.0 
2 0 2 0 0.0 3.4 0.0 0.0 
100.0 90.0 
100.0 90.0 
3 0 3 0 0.0 5.7 0.0 0.0 
100.0 90.0 
100.0 90.0 
"""

		data = {
			"params" : {
				"node_areas" : [-1, 100, 200, 300],
				"run_name" : run_name,
				"time_periods" : [1, 2],
				"num_nodes" : 3,
				"routing_topology" : {
					1 : [1, 20, 30, 40, 50, 60, 70, 80, 90, 100],
					2 : [2, 20, 30, 40, 50, 60, 70, 80, 90, 100],
					3 : [3, 20, 30, 40, 50, 60, 70, 80, 90, 100],
				},
				"istcb1" : None,
				"istcb2" : None,
				"gwmodel_type" : gwmodel_type,
			}
		}
		runoff = [-1, 5, 7, 11, 13, 17, 19]
		with warnings.catch_warnings():
			warnings.filterwarnings("ignore", category=DeprecationWarning)
			sfr = m.get_sfr_file(data, runoff)
		input_output.dump_sfr_output(sfr)
		actual = file_test_helpers.slurp(filename)
		self.assertEqual(expected, actual)
