language: python

python:
  - "3.13"

install: bash setup_linux.sh

jobs:
  include:
    - stage: test
      script: ./test.sh --full
    -
      script: ./test.sh --lint
    - stage: build
      script: ./build.sh
