language: python

python:
  - "3.13"

install: bash setup_linux.sh

jobs:
  include:
    # - stage: test
    #   script: bash test.sh
    # - stage: all-tests
    #   script: bash test.sh --full
    - stage: build
      script: ./test.sh --full && ./build.sh
