import unittest
import swacmod.input_files.input_files_version_2.validation_new as validation_new
import swacmod.input_files.input_files_version_2.specs as specs_module
import datetime

class Test_Validation_New(unittest.TestCase):
    def test_validation_converts_exceptions_to_error_list(self):
        spec_maps = specs_module.make_specs_dictionary(specs_module.make_specs())
        params = make_valid_params()
        params["run_name"] = 5
        actual = validation_new.validate_2(params, spec_maps).errors
        self.assertEqual(
            "---> Validation failed: Parameter \"run_name\" has to be a string, found a <class 'int'> instead",
            actual[0])

    def test_validations_skipped_for_alt_files(self):
        spec_maps = specs_module.make_specs_dictionary(specs_module.make_specs())
        params = make_valid_params()
        params["time_periods"] = "some-alt-file.yml"
        actual = validation_new.validate_2(params, spec_maps).errors
        self.assertEqual(0, len(actual), msg = "\n".join(actual))

    def test_validations_pass_for_valid_input(self):
        spec_maps = specs_module.make_specs_dictionary(specs_module.make_specs())
        params = make_valid_params()
        actual = validation_new.validate_2(params, spec_maps).errors
        self.assertEqual(0, len(actual), msg = "\n".join(actual))

    def test_invalid_values_record_errors(self):
        invalid_pairs = {
            "run_name": 5,
            "num_cores": "x",
            "num_cores": 1000,
            "num_nodes": "x",
            "num_nodes": -1,
            "node_areas": "x",
            "node_areas": {},
            "node_areas": {1: "x", 2: "x", 3: "x"},
            "node_areas": {1: -11, 2: -13, 3: -17},
            "start_date": "x",
            "time_periods": "x",
            "time_periods": [[], [], []],
            "time_periods": [["x", "x"], ["x", "x"], ["x", "x"]],
            "time_periods": [[1, 1], [1, 1], [1, 1]],
            "output_recharge": "x",
            "output_individual": "x",
            "irchcb": "x",
            "nodes_per_line": "x",
            "nodes_per_line": -5,
            "output_fac": "x",
            "output_fac": -5,
            "reporting_zone_names": "x",
            "reporting_zone_names": {1:2, 3:4},
            "rainfall_zone_names": "x",
            "rainfall_zone_names": {1:2, 3:4},
            "rapid_runoff_zone_names": "x",
            "rapid_runoff_zone_names": {1:2, 3:4},
            "pe_zone_names": "x",
            "pe_zone_names": {1:2, 3:4},
            "temperature_zone_names": "x",
            "temperature_zone_names": {1:2, 3:4},
            "tmax_c_zone_names": "x",
            "tmax_c_zone_names": {1:2, 3:4},
            "tmin_c_zone_names": "x",
            "tmin_c_zone_names": {1:2, 3:4},
            "windsp_zone_names": "x",
            "windsp_zone_names": {1:2, 3:4},
            "subroot_zone_names": "x",
            "subroot_zone_names": {1:2, 3:4},
            "rapid_runoff_zone_names": "x",
            "rapid_runoff_zone_names": {1:2, 3:4},
            "swrecharge_zone_names": "x",
            "swrecharge_zone_names": {1:2, 3:4},
            "macropore_zone_names": "x",
            "macropore_zone_names": {1:2, 3:4},
            "soil_zone_names": "x",
            "soil_zone_names": {1:2, 3:4},
            "landuse_zone_names": "x",
            "landuse_zone_names": {1:2, 3:4},
            "canopy_zone_names": "x",
            "canopy_zone_names": {1:2, 3:4},
            "interflow_zone_names": "x",
            "interflow_zone_names": {1:2, 3:4},
            # "sw_zone_names": "x", # TODO: Requires natproc flag.
            # "sw_zone_names": {1:2, 3:4}, # TODO required Natproc flag.
            "canopy_process": "x",
            "canopy_process": 5,
            "snow_process_simple": "x",
            "snow_process_simple": 5,
            "snow_process_complex": "x",
            "snow_process_complex": 5,
            "rapid_runoff_process": "x",
            "rapid_runoff_process": 5,
            "swrecharge_process": "x",
            "swrecharge_process": 5,
            # "single_cell_swrecharge_process": "x", # TODO: Legacy feature (no longer maintained)
            # "single_cell_swrecharge_process": 5, # TODO: Legacy feature (no longer maintained)
            "macropore_process": "x",
            "macropore_process": 5,
            "fao_process": "x",
            "fao_process": 5,
            "subroot_leakage_process": "x",
            "subroot_leakage_process": 5,
            "interflow_process": "x",
            "interflow_process": 5,
            "recharge_attenuation_process": "x",
            "recharge_attenuation_process": 5,
            "historical_solute_process": "x",
            "historical_solute_process": 5,
            "solute_process": "x",
            "solute_process": 5,
            "sw_process": "x",
            "sw_process": 5,
            "sw_ponding_process": "x",
            "sw_ponding_process": 5,
            "routing_process": "x",
            "routing_process": 5,
            "excess_sw_process": "x",
            "excess_sw_process": 5,
            "excess_sw_process": "enabled",
            "recharge_node_mapping": "x",
            "recharge_node_mapping": {"a": "b", "c": "d"},
            "reporting_zone_mapping": "x",
            "reporting_zone_mapping": {"a": "b", "c": "d"},
            "rainfall_zone_mapping": "x",
            "rainfall_zone_mapping": {"a": "b", "c": "d"},
            "pe_zone_mapping": "x",
            "pe_zone_mapping": {"a": "b", "c": "d"},
            "temperature_zone_mapping": "x",
            "temperature_zone_mapping": {"a": "b", "c": "d"},
            "tmax_c_zone_mapping": "x",
            "tmax_c_zone_mapping": {"a": "b", "c": "d"},
            "tmin_c_zone_mapping": "x",
            "tmin_c_zone_mapping": {"a": "b", "c": "d"},
            "windsp_zone_mapping": "x",
            "windsp_zone_mapping": {"a": "b", "c": "d"},
            "subroot_zone_mapping": "x",
            "subroot_zone_mapping": {"a": "b", "c": "d"},
            "rapid_runoff_zone_mapping": "x",
            "rapid_runoff_zone_mapping": {"a": "b", "c": "d"},
            "swrecharge_zone_mapping": "x",
            "swrecharge_zone_mapping": {"a": "b", "c": "d"},
            "macropore_zone_mapping": "x",
            "macropore_zone_mapping": {"a": "b", "c": "d"},
            "canopy_zone_mapping": "x",
            "canopy_zone_mapping": {"a": "b", "c": "d"},
            "interflow_zone_mapping": "x",
            "interflow_zone_mapping": {"a": "b", "c": "d"},
            "sw_zone_mapping": "x",
            "sw_zone_mapping": {"a": "b", "c": "d"},

            "gwmodel_type": 5,
            # "solute_calibration_a": "x", # TODO no validation
            # "solute_calibration_sigma": "x",# TODO no validation
            # "solute_calibration_alpha": "x",# TODO no validation
            # "sw_init_ponding": "x", # TODO validation not called
            # "sw_max_ponding": "x", # TODO validation not called
            "output_sfr": "x",
            # "attenuate_sfr_flows": "x", # TODO no validation
            "istcb1": "x",
            "istcb2": "x",
            # "mf96_lrc": "x", # TODO no validation
            "output_evt": "x",
            "percolation_rejection_use_timeseries": "x",
            "infiltration_limit_use_timeseries": "x",
            "interflow_decay_use_timeseries": "x",
            "fao_input": 5,
            "fao_input": "x",
        }
        spec_maps = specs_module.make_specs_dictionary(specs_module.make_specs())
        for k, v in invalid_pairs.items():
            params = make_valid_params()
            params[k] = v
            actual = validation_new.validate_2(params, spec_maps).errors
            message = f"Expected an error for [{k} = {v}]."
            self.assertNotEqual(0, len(actual), msg = message)

# TODO A similar structure is in test_input_data_v2_validation.py. See if these can be merged.
def make_valid_params():
    return {
        "version": 2,
        "run_name": "my_run",
        "temp_file_backed_array_directory": "temp_scratch_files/",
        "num_nodes": 3,
        "node_areas": {1: 11, 2: 13, 3: 17},
        "node_xy": "node_xy.csv",
        "start_date": datetime.datetime(1980, 1, 1),
        "time_periods": [[1, 2], [3, 4], [5, 6]],
        "num_cores": 1,
        "output_recharge": True,
        "irchcb": 50,
        "nodes_per_line": 5,
        "output_fac": 1.0,
        "spatial_output_date": "1980-01-01",
        "reporting_zone_names": {1:"b", 2:"d"},
        "rainfall_zone_names": {1:"b", 2:"d"},
        "recharge_node_mapping": "rch_nodes.csv",
        "reporting_zone_mapping": {1:1, 2:1, 3:2},
        "rainfall_zone_mapping": {1:[1], 2:[1], 3:[2]},
        "pe_zone_mapping": {1:[1], 2:[1], 3:[2]},
        "temperature_zone_mapping": {1:1, 2:1, 3:2},
        "tmax_c_zone_mapping": {1:1, 2:1, 3:2},
        "tmin_c_zone_mapping": {1:1, 2:1, 3:2},
        "windsp_zone_mapping": {1:1, 2:1, 3:2},
        "subroot_zone_mapping": {1:[1], 2:[1], 3:[2]},
        "rapid_runoff_zone_mapping": {1:1, 2:1, 3:2},
        "swrecharge_zone_mapping": {1:1, 2:1, 3:2},
        "macropore_zone_mapping": {1:1, 2:1, 3:2},
        "canopy_zone_mapping": {1:1, 2:1, 3:2},
        "interflow_zone_mapping": {1:1, 2:1, 3:2},
        "sw_zone_mapping": {1:1, 2:1, 3:2},
        "pe_zone_names": {1:"b", 2:"d"},
        "temperature_zone_names": {1:"b", 2:"d"},
        "tmax_c_zone_names": {1:"b", 2:"d"},
        "tmin_c_zone_names": {1:"b", 2:"d"},
        "windsp_zone_names": {1:"b", 2:"d"},
        "subroot_zone_names": {1:"b", 2:"d"},
        "rapid_runoff_zone_names": {1:"b", 2:"d"},
        "swrecharge_zone_names": {1:"b", 2:"d"},
        "macropore_zone_names": {1:"b", 2:"d"},
        "soil_zone_names": {1:"b", 2:"d"},
        "landuse_zone_names": {1:"b", 2:"d"},
        "canopy_zone_names": {1:"b", 2:"d"},
        "interflow_zone_names": {1:"b", 2:"d"},
        "sw_zone_names": {1:"b", 2:"d"},
        "output_individual": set([1, 2, 3]),
        "canopy_process": "enabled",
        "snow_process_simple": "enabled",
        "snow_process_complex": "enabled",
        "rapid_runoff_process": "enabled",
        "swrecharge_process": "enabled",
        "single_cell_swrecharge_process": "enabled",
        "macropore_process": "enabled",
        "fao_process": "enabled",
        "subroot_leakage_process": "enabled",
        "interflow_process": "enabled",
        "recharge_attenuation_process": "enabled",
        "historical_solute_process": "enabled",
        "solute_process": "enabled",
        "sw_process": "enabled",
        "sw_ponding_process": "enabled",
        "routing_process": "enabled",
        "excess_sw_process": "sw_rip",
        "gwmodel_type": "mf6",
        "solute_calibration_a": 1.38,
        "solute_calibration_sigma": 3.96,
        "solute_calibration_alpha": 3906.25,
        "sw_init_ponding": 5.0,
        "sw_max_ponding": 300.0,
        "output_sfr": True,
        "attenuate_sfr_flows": False,
        "istcb1": 50,
        "istcb2": 55,
        "mf96_lrc": [2, 2, 5],
        "output_evt": True,
        "percolation_rejection_use_timeseries": True,
        "infiltration_limit_use_timeseries": True,
        "interflow_decay_use_timeseries": True,
        "fao_input": 'l',

        "free_throughfall": "free_throughfall.yml",
        "max_canopy_storage": "max_canopy_storage.yml",
        "snow_params_simple": "snow_params.yml",
        "snow_params_complex": "snow_params_complex.yml",
        "rapid_runoff_params": "rapid_runoff_params.yml",
        "swrecharge_proportion": "swrecharge_proportion.yml",
        "swrecharge_limit": "swrecharge_limit.yml",
        "macropore_proportion": "macropore_proportion.yml",
        "macropore_limit": "macropore_limit.yml",
        "macropore_activation": "macropore_activation.yml",
        "macropore_recharge": "macropore_recharge.yml",
        "soil_static_params": "soil_static_params.yml",
        "smd": "smd.yml",
        "soil_spatial": "soil_spatial.yml",
        "lu_spatial": "lu_spatial.yml",
        "zr": "zr.yml",
        "kc": "kc.yml",
        "taw": "taw.yml",
        "raw": "raw.yml",
        "percolation_rejection": "percolation_rejection.yml",
        "percolation_rejection_ts": "percolation_rejection_ts.yml",
        "subroot_leakage_fraction": "subroot_leakage_fraction.yml",
        "init_interflow_store": "init_interflow_store.yml",
        "interflow_store_bypass": "interflow_store_bypass.yml",
        "infiltration_limit": "infiltration_limit.yml",
        "interflow_decay": "interflow_decay.yml",
        "infiltration_limit_ts": "infiltration_limit_ts.yml",
        "interflow_decay_ts": "interflow_decay_ts.yml",
        "recharge_attenuation_params": "recharge_attenuation_params.yml",
        "solute_calibration_mu": "mu.csv",
        "solute_calibration_effective_porosity": "effective_porosity.csv",
        "solute_depth_to_water": "Average_DTW.csv",
        "solute_loading": "NO3_loading.csv",
        "sw_params": "sw_params.yml",
        "sw_downstream": "sw_downstream.yml",
        "sw_activation": "sw_activation.yml",
        "sw_bed_infiltration": "sw_bed_infiltration.yml",
        "sw_direct_recharge": "sw_direct_recharge.yml",
        "sw_pe_to_open_water": "sw_pe_to_open_water.yml",
        "sw_ponding_area": "sw_ponding_area.yml",
        "routing_topology": "routing_parameters.csv",
        "sfr_obs": "gauges_sfr.obs",
        "swdis_ts": "swdis_ts.csv",
        "swdis_locs": "swdis_locs.yml",
        "swabs_ts": "swabs_ts.csv",
        "swabs_locs": "swabs_locs.csv",
        "rainfall_ts": "rainfall_ts.yml",
        "pe_ts": "pe_ts.yml",
        "temperature_ts": "temperature_ts.yml",
        "tmax_c_ts": "tmax_c_ts.yml",
        "tmin_c_ts": "tmin_c_ts.yml",
        "windsp_ts": "windsp_ts.yml",
        "subroot_leakage_ts": "subroot_leakage_ts.yml",
        "evt_parameters": "evt_params.csv",
    }
